ALTER TABLE claims
ADD COLUMN IF NOT EXISTS evaluation JSONB NULL;

ALTER TABLE claims
ADD COLUMN IF NOT EXISTS link_verified BOOLEAN NULL;

ALTER TABLE claims
ADD COLUMN IF NOT EXISTS link_verify_result JSONB NULL;
