-- DropEnum
DROP TYPE "crdb_internal_region";

-- CreateTable
CREATE TABLE "roles" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" STRING NOT NULL,
    "name" STRING NOT NULL,
    "role_type" STRING NOT NULL,
    "can_b_promotion" BOOL NOT NULL DEFAULT false,
    "description" STRING,
    "permissions" STRING NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" STRING NOT NULL,
    "phone" STRING,
    "password_hash" STRING NOT NULL,
    "role" STRING NOT NULL DEFAULT 'part_timer',
    "level" INT4 NOT NULL DEFAULT 1,
    "total_tasks" INT4 NOT NULL DEFAULT 0,
    "total_points" INT4 NOT NULL DEFAULT 0,
    "pass_rate_30d" FLOAT8 NOT NULL DEFAULT 100,
    "last_task_date" TIMESTAMP(3),
    "points" INT4 NOT NULL DEFAULT 0,
    "balance" FLOAT8 NOT NULL DEFAULT 0,
    "b_promotion_points" INT4 NOT NULL DEFAULT 0,
    "invite_code" STRING NOT NULL,
    "invited_by" INT4,
    "c_parent_id" INT4,
    "c_grand_id" INT4,
    "b_inviter_id" INT4,
    "status" INT4 NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "level_configs" (
    "level" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "coefficient" FLOAT8 NOT NULL DEFAULT 1.0,
    "min_tasks" INT4 NOT NULL DEFAULT 0,
    "min_points" INT4 NOT NULL DEFAULT 0,
    "min_pass_rate" FLOAT8 NOT NULL DEFAULT 0,
    "concurrent_tasks" INT4 NOT NULL DEFAULT 1,
    "priority_support" BOOL NOT NULL DEFAULT false,
    "icon" STRING NOT NULL DEFAULT '',
    "is_enabled" BOOL NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "level_configs_pkey" PRIMARY KEY ("level")
);

-- CreateTable
CREATE TABLE "tasks" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "platform" STRING NOT NULL,
    "action" STRING NOT NULL,
    "video_url" STRING,
    "description" STRING NOT NULL,
    "template_images" STRING NOT NULL DEFAULT '[]',
    "requirements" STRING NOT NULL DEFAULT '[]',
    "base_reward" INT4 NOT NULL DEFAULT 0,
    "reward" INT4 NOT NULL DEFAULT 0,
    "remain" INT4 NOT NULL DEFAULT 0,
    "time_limit_minutes" INT4 NOT NULL DEFAULT 10,
    "city_limit" INT4 NOT NULL DEFAULT 1,
    "province_limit" INT4 NOT NULL DEFAULT 4,
    "publisher_type" STRING NOT NULL DEFAULT 'official',
    "publisher_id" INT4,
    "platform_fee_rate" FLOAT8 NOT NULL DEFAULT 0,
    "limit_cities" STRING NOT NULL DEFAULT '[]',
    "daily_limit" INT4 NOT NULL DEFAULT 0,
    "start_time" TIMESTAMP(3),
    "end_time" TIMESTAMP(3),
    "status" STRING NOT NULL DEFAULT 'pending_audit',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tasks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "claims" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "task_id" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "platform" STRING NOT NULL,
    "action" STRING NOT NULL,
    "base_reward" INT4 NOT NULL DEFAULT 0,
    "reward" INT4 NOT NULL DEFAULT 0,
    "level_coefficient" FLOAT8 NOT NULL DEFAULT 1.0,
    "status" STRING NOT NULL DEFAULT 'doing',
    "city" STRING,
    "province" STRING,
    "platform_nickname" STRING,
    "screenshots" STRING NOT NULL DEFAULT '[]',
    "expires_at" TIMESTAMP(3) NOT NULL,
    "claimed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "submitted_at" TIMESTAMP(3),
    "reviewed_at" TIMESTAMP(3),
    "reviewer_id" INT4,
    "review_note" STRING,
    "ai_review_status" STRING,
    "ai_confidence" FLOAT8,
    "ai_reason" STRING,
    "ai_reviewed_at" TIMESTAMP(3),
    "image_review_status" STRING,
    "image_reviewed_at" TIMESTAMP(3),
    "image_review_reason" STRING,
    "link_review_status" STRING,
    "link_reviewed_at" TIMESTAMP(3),
    "link_review_reason" STRING,

    CONSTRAINT "claims_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "records" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "type" STRING NOT NULL,
    "desc" STRING NOT NULL,
    "points" INT4 NOT NULL DEFAULT 0,
    "balance" FLOAT8 NOT NULL DEFAULT 0,
    "extra_data" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "promotion_relations" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" STRING NOT NULL,
    "parent_id" INT4 NOT NULL,
    "child_id" INT4 NOT NULL,
    "level" INT4 NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "promotion_relations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "promotion_earnings" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" STRING NOT NULL,
    "user_id" INT4 NOT NULL,
    "from_user_id" INT4 NOT NULL,
    "from_claim_id" INT4,
    "level" INT4 NOT NULL DEFAULT 1,
    "points" INT4 NOT NULL DEFAULT 0,
    "source_points" INT4 NOT NULL DEFAULT 0,
    "rate" FLOAT8 NOT NULL DEFAULT 0,
    "status" STRING NOT NULL DEFAULT 'settled',
    "settled_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "promotion_earnings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "leaderboard_snapshots" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" STRING NOT NULL,
    "stat_date" TIMESTAMP(3) NOT NULL,
    "user_id" INT4 NOT NULL,
    "rank_no" INT4 NOT NULL,
    "points" INT4 NOT NULL DEFAULT 0,
    "task_count" INT4 NOT NULL DEFAULT 0,
    "level" INT4 NOT NULL DEFAULT 1,
    "is_verified" BOOL NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "leaderboard_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "leaderboard_rewards" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" STRING NOT NULL,
    "stat_date" TIMESTAMP(3) NOT NULL,
    "user_id" INT4 NOT NULL,
    "rank_no" INT4 NOT NULL,
    "points" INT4 NOT NULL DEFAULT 0,
    "title" STRING,
    "extra_privileges" STRING,
    "status" STRING NOT NULL DEFAULT 'pending',
    "issued_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "leaderboard_rewards_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "system_configs" (
    "key" STRING NOT NULL,
    "value" STRING NOT NULL,
    "description" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_configs_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "withdrawals" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "type" STRING NOT NULL DEFAULT 'part_time',
    "amount" FLOAT8 NOT NULL,
    "points" INT4 NOT NULL DEFAULT 0,
    "status" STRING NOT NULL DEFAULT 'pending',
    "wechat_info" STRING,
    "reviewed_at" TIMESTAMP(3),
    "reviewer_id" INT4,
    "review_note" STRING,
    "paid_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "withdrawals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "configs" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key" STRING NOT NULL,
    "value" STRING NOT NULL,
    "desc" STRING,

    CONSTRAINT "configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_conversations" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "type" STRING NOT NULL,
    "title" STRING,
    "context" STRING NOT NULL DEFAULT '{}',
    "status" STRING NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_conversations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_messages" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "conversation_id" INT4 NOT NULL,
    "role" STRING NOT NULL,
    "content" STRING NOT NULL,
    "metadata" STRING NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_operation_logs" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "type" STRING NOT NULL,
    "action" STRING NOT NULL,
    "input" STRING NOT NULL DEFAULT '{}',
    "output" STRING NOT NULL DEFAULT '{}',
    "status" STRING NOT NULL DEFAULT 'success',
    "error_msg" STRING,
    "duration" INT4 NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_operation_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_configs" (
    "key" STRING NOT NULL,
    "value" STRING NOT NULL,
    "type" STRING NOT NULL DEFAULT 'text',
    "description" STRING,
    "category" STRING NOT NULL DEFAULT 'general',
    "is_enabled" BOOL NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_configs_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "ai_review_queue" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "claim_id" INT4 NOT NULL,
    "user_id" INT4 NOT NULL,
    "task_id" INT4 NOT NULL,
    "screenshots" STRING NOT NULL DEFAULT '[]',
    "ai_result" STRING,
    "ai_confidence" FLOAT8,
    "ai_reason" STRING,
    "status" STRING NOT NULL DEFAULT 'pending',
    "priority" INT4 NOT NULL DEFAULT 0,
    "retry_count" INT4 NOT NULL DEFAULT 0,
    "processed_at" TIMESTAMP(3),
    "processed_by" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_review_queue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_screenshot_fingerprints" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "claim_id" INT4,
    "image_url" STRING NOT NULL,
    "fingerprint" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'valid',
    "reason" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_screenshot_fingerprints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_credit_scores" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "score" INT4 NOT NULL DEFAULT 50,
    "level" STRING NOT NULL DEFAULT 'normal',
    "pass_rate_score" FLOAT8 NOT NULL DEFAULT 0,
    "speed_score" FLOAT8 NOT NULL DEFAULT 0,
    "frequency_score" FLOAT8 NOT NULL DEFAULT 0,
    "cheat_score" FLOAT8 NOT NULL DEFAULT 0,
    "random_check_rate" FLOAT8 NOT NULL DEFAULT 0.05,
    "stats_snapshot" STRING NOT NULL DEFAULT '{}',
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_credit_scores_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "login_logs" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4,
    "username" STRING,
    "login_status" STRING NOT NULL DEFAULT 'success',
    "failure_reason" STRING,
    "ip_address" STRING,
    "location" STRING,
    "device" STRING,
    "user_agent" STRING,
    "login_time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "logout_time" TIMESTAMP(3),
    "is_anomaly" BOOL NOT NULL DEFAULT false,
    "anomaly_reason" STRING,

    CONSTRAINT "login_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "operation_logs" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "admin_id" INT4,
    "admin_name" STRING,
    "operator_role" STRING,
    "action" STRING NOT NULL,
    "target_type" STRING,
    "target_id" INT4,
    "target_name" STRING,
    "description" STRING,
    "old_value" STRING,
    "new_value" STRING,
    "ip_address" STRING,
    "user_agent" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "operation_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "system_logs" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "level" STRING NOT NULL DEFAULT 'info',
    "type" STRING,
    "message" STRING NOT NULL,
    "context" STRING,
    "user_id" INT4,
    "username" STRING,
    "ip_address" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "system_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_alerts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "alert_type" STRING NOT NULL,
    "alert_level" STRING NOT NULL DEFAULT 'info',
    "user_id" INT4,
    "ip_address" STRING,
    "location" STRING,
    "alert_detail" STRING NOT NULL DEFAULT '{}',
    "is_resolved" BOOL NOT NULL DEFAULT false,
    "resolved_by" INT4,
    "resolved_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_alerts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "suspicious_users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "username" STRING,
    "reason" STRING,
    "risk_level" STRING NOT NULL DEFAULT 'medium',
    "evidence" STRING NOT NULL DEFAULT '{}',
    "status" STRING NOT NULL DEFAULT 'monitoring',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "suspicious_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "achievements" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING,
    "condition_type" STRING NOT NULL,
    "condition_value" INT4 NOT NULL,
    "reward_points" INT4 NOT NULL DEFAULT 0,
    "sort_order" INT4 NOT NULL DEFAULT 0,
    "is_active" BOOL NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "achievements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_achievements" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "achievement_id" INT4 NOT NULL,
    "achieved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_achievements_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "roles_code_key" ON "roles"("code");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "users_invite_code_key" ON "users"("invite_code");

-- CreateIndex
CREATE INDEX "users_username_idx" ON "users"("username");

-- CreateIndex
CREATE INDEX "users_role_idx" ON "users"("role");

-- CreateIndex
CREATE INDEX "users_level_idx" ON "users"("level");

-- CreateIndex
CREATE INDEX "users_c_parent_id_idx" ON "users"("c_parent_id");

-- CreateIndex
CREATE INDEX "users_b_inviter_id_idx" ON "users"("b_inviter_id");

-- CreateIndex
CREATE INDEX "tasks_platform_idx" ON "tasks"("platform");

-- CreateIndex
CREATE INDEX "tasks_status_idx" ON "tasks"("status");

-- CreateIndex
CREATE INDEX "tasks_publisher_type_idx" ON "tasks"("publisher_type");

-- CreateIndex
CREATE INDEX "claims_user_id_idx" ON "claims"("user_id");

-- CreateIndex
CREATE INDEX "claims_task_id_idx" ON "claims"("task_id");

-- CreateIndex
CREATE INDEX "claims_status_idx" ON "claims"("status");

-- CreateIndex
CREATE INDEX "claims_ai_review_status_idx" ON "claims"("ai_review_status");

-- CreateIndex
CREATE INDEX "records_user_id_idx" ON "records"("user_id");

-- CreateIndex
CREATE INDEX "records_type_idx" ON "records"("type");

-- CreateIndex
CREATE INDEX "promotion_relations_type_parent_id_idx" ON "promotion_relations"("type", "parent_id");

-- CreateIndex
CREATE INDEX "promotion_relations_type_child_id_idx" ON "promotion_relations"("type", "child_id");

-- CreateIndex
CREATE UNIQUE INDEX "promotion_relations_type_parent_id_child_id_key" ON "promotion_relations"("type", "parent_id", "child_id");

-- CreateIndex
CREATE INDEX "promotion_earnings_type_user_id_status_idx" ON "promotion_earnings"("type", "user_id", "status");

-- CreateIndex
CREATE INDEX "promotion_earnings_from_user_id_idx" ON "promotion_earnings"("from_user_id");

-- CreateIndex
CREATE INDEX "leaderboard_snapshots_type_user_id_stat_date_idx" ON "leaderboard_snapshots"("type", "user_id", "stat_date");

-- CreateIndex
CREATE UNIQUE INDEX "leaderboard_snapshots_type_stat_date_rank_no_key" ON "leaderboard_snapshots"("type", "stat_date", "rank_no");

-- CreateIndex
CREATE INDEX "leaderboard_rewards_type_stat_date_status_idx" ON "leaderboard_rewards"("type", "stat_date", "status");

-- CreateIndex
CREATE UNIQUE INDEX "leaderboard_rewards_type_stat_date_user_id_key" ON "leaderboard_rewards"("type", "stat_date", "user_id");

-- CreateIndex
CREATE INDEX "withdrawals_user_id_idx" ON "withdrawals"("user_id");

-- CreateIndex
CREATE INDEX "withdrawals_status_idx" ON "withdrawals"("status");

-- CreateIndex
CREATE INDEX "withdrawals_type_idx" ON "withdrawals"("type");

-- CreateIndex
CREATE UNIQUE INDEX "configs_key_key" ON "configs"("key");

-- CreateIndex
CREATE INDEX "ai_conversations_user_id_idx" ON "ai_conversations"("user_id");

-- CreateIndex
CREATE INDEX "ai_conversations_type_idx" ON "ai_conversations"("type");

-- CreateIndex
CREATE INDEX "ai_conversations_status_idx" ON "ai_conversations"("status");

-- CreateIndex
CREATE INDEX "ai_messages_conversation_id_idx" ON "ai_messages"("conversation_id");

-- CreateIndex
CREATE INDEX "ai_operation_logs_user_id_idx" ON "ai_operation_logs"("user_id");

-- CreateIndex
CREATE INDEX "ai_operation_logs_type_idx" ON "ai_operation_logs"("type");

-- CreateIndex
CREATE INDEX "ai_operation_logs_status_idx" ON "ai_operation_logs"("status");

-- CreateIndex
CREATE INDEX "ai_configs_category_idx" ON "ai_configs"("category");

-- CreateIndex
CREATE UNIQUE INDEX "ai_review_queue_claim_id_key" ON "ai_review_queue"("claim_id");

-- CreateIndex
CREATE INDEX "ai_review_queue_claim_id_idx" ON "ai_review_queue"("claim_id");

-- CreateIndex
CREATE INDEX "ai_review_queue_status_idx" ON "ai_review_queue"("status");

-- CreateIndex
CREATE INDEX "ai_review_queue_priority_idx" ON "ai_review_queue"("priority");

-- CreateIndex
CREATE INDEX "ai_screenshot_fingerprints_fingerprint_idx" ON "ai_screenshot_fingerprints"("fingerprint");

-- CreateIndex
CREATE INDEX "ai_screenshot_fingerprints_user_id_idx" ON "ai_screenshot_fingerprints"("user_id");

-- CreateIndex
CREATE INDEX "ai_screenshot_fingerprints_claim_id_idx" ON "ai_screenshot_fingerprints"("claim_id");

-- CreateIndex
CREATE INDEX "ai_screenshot_fingerprints_status_idx" ON "ai_screenshot_fingerprints"("status");

-- CreateIndex
CREATE UNIQUE INDEX "user_credit_scores_user_id_key" ON "user_credit_scores"("user_id");

-- CreateIndex
CREATE INDEX "user_credit_scores_score_idx" ON "user_credit_scores"("score");

-- CreateIndex
CREATE INDEX "user_credit_scores_level_idx" ON "user_credit_scores"("level");

-- CreateIndex
CREATE INDEX "login_logs_user_id_idx" ON "login_logs"("user_id");

-- CreateIndex
CREATE INDEX "login_logs_username_idx" ON "login_logs"("username");

-- CreateIndex
CREATE INDEX "login_logs_login_time_idx" ON "login_logs"("login_time");

-- CreateIndex
CREATE INDEX "login_logs_login_status_idx" ON "login_logs"("login_status");

-- CreateIndex
CREATE INDEX "login_logs_is_anomaly_idx" ON "login_logs"("is_anomaly");

-- CreateIndex
CREATE INDEX "operation_logs_admin_id_idx" ON "operation_logs"("admin_id");

-- CreateIndex
CREATE INDEX "operation_logs_action_idx" ON "operation_logs"("action");

-- CreateIndex
CREATE INDEX "operation_logs_target_type_idx" ON "operation_logs"("target_type");

-- CreateIndex
CREATE INDEX "operation_logs_created_at_idx" ON "operation_logs"("created_at");

-- CreateIndex
CREATE INDEX "system_logs_level_idx" ON "system_logs"("level");

-- CreateIndex
CREATE INDEX "system_logs_type_idx" ON "system_logs"("type");

-- CreateIndex
CREATE INDEX "system_logs_created_at_idx" ON "system_logs"("created_at");

-- CreateIndex
CREATE INDEX "system_logs_user_id_idx" ON "system_logs"("user_id");

-- CreateIndex
CREATE INDEX "audit_alerts_user_id_idx" ON "audit_alerts"("user_id");

-- CreateIndex
CREATE INDEX "audit_alerts_alert_type_idx" ON "audit_alerts"("alert_type");

-- CreateIndex
CREATE INDEX "audit_alerts_created_at_idx" ON "audit_alerts"("created_at");

-- CreateIndex
CREATE INDEX "audit_alerts_is_resolved_idx" ON "audit_alerts"("is_resolved");

-- CreateIndex
CREATE INDEX "suspicious_users_user_id_idx" ON "suspicious_users"("user_id");

-- CreateIndex
CREATE INDEX "suspicious_users_status_idx" ON "suspicious_users"("status");

-- CreateIndex
CREATE UNIQUE INDEX "achievements_name_key" ON "achievements"("name");

-- CreateIndex
CREATE UNIQUE INDEX "user_achievements_user_id_achievement_id_key" ON "user_achievements"("user_id", "achievement_id");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "claims" ADD CONSTRAINT "claims_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claims" ADD CONSTRAINT "claims_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "records" ADD CONSTRAINT "records_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "promotion_relations" ADD CONSTRAINT "promotion_relations_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "promotion_relations" ADD CONSTRAINT "promotion_relations_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "promotion_earnings" ADD CONSTRAINT "promotion_earnings_from_claim_id_fkey" FOREIGN KEY ("from_claim_id") REFERENCES "claims"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "promotion_earnings" ADD CONSTRAINT "promotion_earnings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "leaderboard_snapshots" ADD CONSTRAINT "leaderboard_snapshots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "leaderboard_rewards" ADD CONSTRAINT "leaderboard_rewards_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "withdrawals" ADD CONSTRAINT "withdrawals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_messages" ADD CONSTRAINT "ai_messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_achievement_id_fkey" FOREIGN KEY ("achievement_id") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE CASCADE;
